/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package de.orat.math.cga.api;

/**
 * Boosts are generated by a lightlike Tangent T = oe 1 + oe 2 + oe 3 with T 2 = 0 and
 * weighted bases. Boosts, also known as constant accelerations, transversors, or spe-
 * cial conformal transformations, can play a role in calculating relativity dynamics, as
 * a differential that moves along various orbits. Here we observe how they can be used
 * to bend lines into circles, and planes into spheres. Consid
 * 
 * @author Oliver Rettig (Oliver.Rettig@orat.de)
 */
public class CGABoost extends CGAMultivector {
    
}
