package de.orat.math.cga.api;

/**
 * Boosts are generated by a lightlike Tangent T = oe1 + oe2 + oe3 
 * with sqr(T) = 0 and weighted bases. 
 * 
 * Boosts, also known as constant accelerations, transversors, or special 
 * conformal transformations, can play a role in calculating relativity dynamics, 
 * as a differential that moves along various orbits. Here we observe how they 
 * can be used to bend lines into circles, and planes into spheres. 
 * 
 * @author Oliver Rettig (Oliver.Rettig@orat.de)
 */
public class CGABoost extends CGAMultivector {
    
    public CGABoost(CGAMultivector m){
        super(m.impl);
    }
    
    // TODO
}
