/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package de.orat.math.cga.api;

/**
 * Dilation rotors about the origin are generated by the timelike Minkowski Plane E =
 * o ∧ ∞ with E 2 > 0 and weighted base. A dilatation around any point in space can be
 * constructed by translating the Dilator D.
 * 
 * @author Oliver Rettig (Oliver.Rettig@orat.de)
 */
public class CGADilator extends CGAMultivector {
    
}
